NETWORK = 'ton'
NETWORK_NATIVE_CURRENCY_ADDRESS = 'EQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAM9c'
UPDATES_COOLDOWN = 60
GECKO_TERMINAL_MAX_REQUESTS_PER_CYCLE = 10
ALERTS_CHANGE_BOUND = 0.05
ALERTS_COOLDOWN = 60 * 30
LOGGING_FORMAT = '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
TOKEN_BLACKLIST = {
    'USDT': 'EQCxE6mUtQJKFnGfaROTKOt1lZbDiiX1kCixRv7Nw2Id_sDs',
    'jUSDT': 'EQBynBO23ywHy_CgarY9NK9FTz0yDsG82PtcbSTQgGoXwiuA',
}
